# Generated by Django 3.0.1 on 2020-01-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0002_auto_20200102_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
