# Generated by Django 3.0.1 on 2020-01-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appmain', '0003_delete_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('team_abrev', models.CharField(max_length=3)),
                ('web_address', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('logo_file_name', models.CharField(max_length=50)),
                ('win', models.SmallIntegerField()),
                ('lose', models.SmallIntegerField()),
                ('tie', models.SmallIntegerField()),
                ('conference', models.CharField(max_length=50)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('closed', models.BinaryField()),
                ('closed_by', models.CharField(max_length=50)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('actual_date_closed', models.DateTimeField(blank=True, null=True)),
                ('forecast_date_closed', models.DateTimeField(blank=True, null=True)),
                ('graphics_folder', models.CharField(max_length=100)),
                ('standings_report_ran', models.BinaryField()),
                ('weekly_standings_html', models.TextField()),
                ('mobile_standings_report_ran', models.BinaryField()),
                ('mobile_weekly_standings_html', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year_id', models.PositiveSmallIntegerField()),
                ('game_number', models.PositiveSmallIntegerField()),
                ('game_date', models.DateField()),
                ('points_game', models.BinaryField()),
                ('tv_network', models.CharField(max_length=10)),
                ('home_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='appmain.Team')),
                ('visitor_team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_team', to='appmain.Team')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week', to='appmain.Week')),
            ],
        ),
    ]
