# Generated by Django 3.0.1 on 2020-01-06 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='ball_pool',
            field=models.BinaryField(default=(0).to_bytes(2,byteorder='big')),
        ),
        migrations.AddField(
            model_name='profile',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_team', to='appmain.Team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intro_sound',
            field=models.BinaryField(default=(0).to_bytes(2,byteorder='big')),
        ),
        migrations.AddField(
            model_name='profile',
            name='king_hill_eligable',
            field=models.BinaryField(default=(0).to_bytes(2,byteorder='big')),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_graphics',
            field=models.BinaryField(default=(0).to_bytes(2,byteorder='big')),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_video',
            field=models.BinaryField(default=(0).to_bytes(2,byteorder='big')),
        ),
        migrations.AlterField(
            model_name='team',
            name='web_address',
            field=models.URLField(),
        ),
    ]
