# Generated by Django 3.0.1 on 2020-01-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0007_auto_20200105_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ball_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='intro_sound',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='king_hill_eligable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_graphics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='show_video',
            field=models.BooleanField(default=False),
        ),
    ]
