# Generated by Django 3.0.1 on 2020-01-06 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0008_auto_20200105_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ball_pool',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='intro_sound',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='king_hill_eligable',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_graphics',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_video',
        ),
    ]
