# Generated by Django 3.0.1 on 2020-01-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0009_auto_20200105_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ball_pool',
            field=models.BooleanField(default=False),
        ),
    ]
