# Generated by Django 3.0.1 on 2020-01-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0010_profile_ball_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro_sound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='king_hill_eligable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_graphics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_video',
            field=models.BooleanField(default=False),
        ),
    ]
