# Generated by Django 3.0.1 on 2020-01-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0012_auto_20200107_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='points_game',
            field=models.BooleanField(default=False),
        ),
    ]
