# Generated by Django 3.0.1 on 2020-01-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0013_auto_20200107_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='entered_by',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pick',
            name='updated_by',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='pick',
            name='user_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='postpick',
            name='user_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='postresult',
            name='updated_by',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='updated_by',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
