# Generated by Django 3.0.1 on 2020-01-08 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0014_auto_20200107_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='entered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pick',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pick',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postpick',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postresult',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='result',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
