# Generated by Django 3.0.1 on 2020-01-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0015_auto_20200108_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='NflGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=10)),
                ('gsis', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=3)),
                ('time', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=3)),
                ('k', models.CharField(max_length=1)),
                ('home', models.CharField(max_length=3)),
                ('home_name', models.CharField(max_length=20)),
                ('home_score', models.PositiveSmallIntegerField()),
                ('visitor', models.CharField(max_length=3)),
                ('visitor_name', models.CharField(max_length=20)),
                ('visitor_score', models.PositiveSmallIntegerField()),
                ('p', models.CharField(max_length=1)),
                ('red_zone', models.CharField(max_length=1)),
                ('ga', models.CharField(max_length=1)),
                ('gt', models.CharField(max_length=3)),
            ],
        ),
    ]
