# Generated by Django 3.0.1 on 2020-01-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0016_nflgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflgame',
            name='home_score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nflgame',
            name='time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
