# Generated by Django 3.0.1 on 2020-01-08 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0018_auto_20200108_0812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nflgame',
            options={'ordering': ['gsis']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='week',
        ),
        migrations.AddField(
            model_name='game',
            name='wk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_wk', to='appmain.Week'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nflgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nflgame',
            name='gd',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='t',
            field=models.CharField(default='P', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nflgame',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='wk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nflgame_wk', to='appmain.Week'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='week_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='week',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='mobile_standings_report_ran',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='week',
            name='standings_report_ran',
            field=models.BooleanField(default=False),
        ),
    ]
