# Generated by Django 3.0.1 on 2020-01-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0019_auto_20200108_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflgame',
            name='created',
        ),
        migrations.RemoveField(
            model_name='nflgame',
            name='updated',
        ),
    ]
