# Generated by Django 3.0.1 on 2020-01-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0020_auto_20200108_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nflgame',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='nflgame',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
