# Generated by Django 3.0.1 on 2020-01-10 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0024_auto_20200109_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='team_id',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
