# Generated by Django 3.0.1 on 2020-01-10 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0025_auto_20200109_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gd', models.PositiveSmallIntegerField(null=True)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('t', models.CharField(max_length=10)),
                ('eid', models.CharField(max_length=10)),
                ('gsis', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=3)),
                ('time', models.CharField(max_length=5, null=True)),
                ('status', models.CharField(max_length=3)),
                ('k', models.CharField(max_length=1)),
                ('home', models.CharField(max_length=3)),
                ('home_name', models.CharField(max_length=20)),
                ('home_score', models.PositiveSmallIntegerField(null=True)),
                ('visitor', models.CharField(max_length=3)),
                ('visitor_name', models.CharField(max_length=20)),
                ('visitor_score', models.PositiveSmallIntegerField(null=True)),
                ('p', models.CharField(max_length=1)),
                ('red_zone', models.CharField(max_length=1)),
                ('ga', models.CharField(max_length=2)),
                ('gt', models.CharField(max_length=3)),
                ('wk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_wk', to='appmain.Week')),
            ],
            options={
                'ordering': ['gsis'],
            },
        ),
        migrations.DeleteModel(
            name='NflGame',
        ),
    ]
