# Generated by Django 3.0.1 on 2020-01-10 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0026_auto_20200109_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='date_entered',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='date_updated',
        ),
    ]
