# Generated by Django 3.0.1 on 2020-01-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0027_auto_20200110_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.PositiveSmallIntegerField(default=2018, primary_key=True, serialize=False)),
            ],
        ),
    ]
