# Generated by Django 3.0.1 on 2020-01-10 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0029_week_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pick_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pick',
            name='wk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_wk', to='appmain.Week'),
        ),
    ]
