# Generated by Django 3.0.1 on 2020-01-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0030_auto_20200110_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='wk',
            new_name='wk_no',
        ),
    ]
