# Generated by Django 3.0.1 on 2020-01-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0031_auto_20200110_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='wk_no',
        ),
    ]
