# Generated by Django 3.0.1 on 2020-01-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0032_remove_game_wk_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_wk', to='appmain.Week'),
        ),
        migrations.AddField(
            model_name='game',
            name='wk_no',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
