# Generated by Django 3.0.1 on 2020-01-10 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0034_pick_koth_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_game_entered', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_game', to='appmain.Game')),
                ('pick_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_head', to='appmain.Pick')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_team', to='appmain.Team')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_game_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
