# Generated by Django 3.0.1 on 2020-01-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0035_pickgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week_no',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
