# Generated by Django 3.0.1 on 2020-01-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0036_auto_20200110_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='week_no',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
