# Generated by Django 3.0.1 on 2020-01-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0037_auto_20200110_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='year',
        ),
        migrations.AlterField(
            model_name='week',
            name='closed_by',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='graphics_folder',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
