# Generated by Django 3.0.1 on 2020-01-10 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0038_auto_20200110_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
