# Generated by Django 3.0.1 on 2020-01-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0039_delete_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('year', models.PositiveSmallIntegerField(default=2018, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
