# Generated by Django 3.0.1 on 2020-01-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0040_season'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
