# Generated by Django 3.0.1 on 2020-01-10 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0044_auto_20200110_1610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
    ]
