# Generated by Django 3.0.1 on 2020-01-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0050_auto_20200113_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_teamname',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
