# Generated by Django 3.0.1 on 2020-01-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0053_game_visitor_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bf',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='bph',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ga',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='gt',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_nickname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_teamname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='k',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='p',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='red_zone',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='t',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitor_nickname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='visitor_teamname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
