# Generated by Django 3.0.1 on 2020-01-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0054_auto_20200113_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickgame',
            name='pick_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appmain.Pick'),
        ),
    ]
