# Generated by Django 3.0.1 on 2020-01-17 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0055_auto_20200117_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='appmain.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='visitor_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='appmain.Team'),
            preserve_default=False,
        ),
    ]
