# Generated by Django 3.0.1 on 2020-01-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0056_auto_20200117_1605'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pick',
            constraint=models.UniqueConstraint(fields=('user', 'wk'), name='pick_user_wk'),
        ),
    ]
