# Generated by Django 3.0.1 on 2020-01-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0058_game_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
