# Generated by Django 3.0.1 on 2020-01-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0059_auto_20200120_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='koth_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koth_game', to='appmain.Game'),
        ),
    ]
