# Generated by Django 3.0.1 on 2020-01-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0060_pick_koth_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
