# Generated by Django 3.0.1 on 2020-01-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0061_pick_saved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='yr',
            new_name='year',
        ),
    ]
