# Generated by Django 3.0.1 on 2020-01-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0062_auto_20200124_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['year'], 'verbose_name': 'season', 'verbose_name_plural': 'seasons'},
        ),
        migrations.AlterField(
            model_name='season',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['year', 'current'], name='appmain_sea_year_a5e4b8_idx'),
        ),
    ]
