# Generated by Django 3.0.1 on 2020-01-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0063_auto_20200124_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['year', 'week_no'], 'verbose_name': 'week', 'verbose_name_plural': 'weeks'},
        ),
        migrations.AddIndex(
            model_name='week',
            index=models.Index(fields=['year', 'week_no', 'gt', 'closed'], name='appmain_wee_year_id_557099_idx'),
        ),
    ]
