# Generated by Django 3.0.1 on 2020-01-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0064_auto_20200124_1035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['gsis'], 'verbose_name': 'game', 'verbose_name_plural': 'games'},
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['week', 'year', 'eid', 'gsis'], name='appmain_gam_week_id_ae8989_idx'),
        ),
    ]
