# Generated by Django 3.0.1 on 2020-01-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0065_auto_20200124_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_abrev'], 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.RemoveField(
            model_name='week',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='week',
            name='start_date',
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['team_abrev', 'short_name'], name='appmain_tea_team_ab_793b77_idx'),
        ),
    ]
