# Generated by Django 3.0.1 on 2020-01-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0066_auto_20200124_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='forecast_date_closed',
        ),
    ]
