# Generated by Django 3.0.1 on 2020-01-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0067_remove_week_forecast_date_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
