# Generated by Django 3.0.1 on 2020-01-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0068_week_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
