# Generated by Django 3.0.1 on 2020-01-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0069_week_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='forecast_date_closed',
            field=models.DateField(null=True),
        ),
    ]
