# Generated by Django 3.0.1 on 2020-01-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0070_week_forecast_date_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='week',
            name='forecast_date_closed',
        ),
        migrations.RemoveField(
            model_name='week',
            name='start_date',
        ),
    ]
