# Generated by Django 3.0.1 on 2020-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0071_auto_20200124_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='forecast_date_closed',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
