# Generated by Django 3.0.1 on 2020-01-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0073_auto_20200124_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pick',
            options={'ordering': ['user', 'wk'], 'verbose_name': 'pick', 'verbose_name_plural': 'picks'},
        ),
        migrations.AlterModelOptions(
            name='pickgame',
            options={'verbose_name': 'pick game', 'verbose_name_plural': 'pick games'},
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['user', 'wk'], name='appmain_pic_user_id_bb14af_idx'),
        ),
    ]
