# Generated by Django 3.0.1 on 2020-01-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0074_auto_20200125_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='pick_score',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
