# Generated by Django 3.0.1 on 2020-01-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0076_auto_20200127_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickgame',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.Game'),
        ),
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='forecast_date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='graphics_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='mobile_weekly_standings_html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='weekly_standings_html',
            field=models.TextField(blank=True),
        ),
    ]
