# Generated by Django 3.0.1 on 2020-01-31 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0077_auto_20200131_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickgame',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_game', to='appmain.Game'),
        ),
    ]
