# Generated by Django 3.0.1 on 2020-02-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0079_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickgame',
            name='status',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
