# Generated by Django 3.0.1 on 2020-02-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0080_pickgame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='network',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
