# Generated by Django 3.0.1 on 2020-02-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0081_game_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points_game',
            field=models.BooleanField(default=False),
        ),
    ]
