# Generated by Django 3.0.1 on 2020-02-11 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0082_game_points_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveSmallIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed', to='appmain.Team')),
            ],
            options={
                'verbose_name': 'seed',
                'verbose_name_plural': 'seeds',
                'ordering': ['team', 'seed'],
            },
        ),
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['team'], name='appmain_see_team_id_d799d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='seed',
            constraint=models.UniqueConstraint(fields=('team',), name='team_seed'),
        ),
    ]
