# Generated by Django 3.0.1 on 2020-02-11 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0083_auto_20200211_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seed',
            options={'ordering': ['year', 'team', 'seed'], 'verbose_name': 'seed', 'verbose_name_plural': 'seeds'},
        ),
        migrations.RemoveConstraint(
            model_name='seed',
            name='team_seed',
        ),
        migrations.RemoveIndex(
            model_name='seed',
            name='appmain_see_team_id_d799d5_idx',
        ),
        migrations.AddField(
            model_name='seed',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.Season'),
        ),
        migrations.AddIndex(
            model_name='seed',
            index=models.Index(fields=['year', 'team'], name='appmain_see_year_id_4a2f74_idx'),
        ),
        migrations.AddConstraint(
            model_name='seed',
            constraint=models.UniqueConstraint(fields=('year', 'team'), name='year_team'),
        ),
    ]
