# Generated by Django 3.0.1 on 2020-02-13 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0085_seed_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('pick_score', models.PositiveSmallIntegerField(default=0)),
                ('saved', models.BooleanField(default=False)),
                ('round_id', models.PositiveSmallIntegerField()),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pick_entered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pick_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post season pick',
                'verbose_name_plural': 'post season picks',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='PostPickGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_type', models.CharField(choices=[('AWC45', 'AFC Wild Card 45'), ('AWC36', 'AFC Wild Card 36'), ('ADIV1', 'AFC Divisional 1'), ('ADIV2', 'AFC Divisional 2'), ('ACONF', 'AFC Conferance Champ'), ('NWC45', 'NFC Wild Card 45'), ('NWC36', 'NFC Wild Card 36'), ('NDIV1', 'NFC Divisional 1'), ('NDIV2', 'NFC Divisional 2'), ('NCONF', 'AFC Conferance Champ'), ('SB', 'Super Bowl')], max_length=5)),
                ('status', models.CharField(max_length=1, null=True)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pick_game_entered', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pick_game', to='appmain.Game')),
                ('post_pick_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_games', to='appmain.PostPick')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_pick_team', to='appmain.Team')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_post_pick_game_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'post seasin pick game',
                'verbose_name_plural': 'post seasonpick games',
            },
        ),
        migrations.AddIndex(
            model_name='postpick',
            index=models.Index(fields=['user'], name='appmain_pos_user_id_bdf5bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='postpick',
            constraint=models.UniqueConstraint(fields=('user',), name='ps_pick_user'),
        ),
    ]
