# Generated by Django 3.0.1 on 2020-02-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0087_auto_20200213_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpickgame',
            name='ps_type',
        ),
    ]
