# Generated by Django 3.0.1 on 2020-02-14 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0089_postpickgame_ps_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeds', to='appmain.Team'),
        ),
    ]
