# Generated by Django 3.0.1 on 2020-02-17 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0090_auto_20200214_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpick',
            name='year',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.Season'),
        ),
    ]
