# Generated by Django 3.0.1 on 2020-02-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0092_auto_20200217_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField()),
                ('wk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rnd_points', to='appmain.Week')),
            ],
            options={
                'verbose_name': 'point',
                'verbose_name_plural': 'points',
                'ordering': ['wk'],
            },
        ),
        migrations.AddIndex(
            model_name='postpoint',
            index=models.Index(fields=['wk'], name='appmain_pos_wk_id_50cc72_idx'),
        ),
        migrations.AddConstraint(
            model_name='postpoint',
            constraint=models.UniqueConstraint(fields=('wk',), name='wk_pts'),
        ),
    ]
