# Generated by Django 3.0.1 on 2020-02-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0093_auto_20200217_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpoint',
            options={'ordering': ['gt'], 'verbose_name': 'point', 'verbose_name_plural': 'points'},
        ),
        migrations.RemoveConstraint(
            model_name='postpoint',
            name='wk_pts',
        ),
        migrations.RemoveIndex(
            model_name='postpoint',
            name='appmain_pos_wk_id_50cc72_idx',
        ),
        migrations.AddField(
            model_name='postpoint',
            name='gt',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddIndex(
            model_name='postpoint',
            index=models.Index(fields=['gt'], name='appmain_pos_gt_e0b3f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='postpoint',
            constraint=models.UniqueConstraint(fields=('gt',), name='gt_pts'),
        ),
    ]
