# Generated by Django 3.0.1 on 2020-02-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0095_remove_postpoint_wk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weeks', to='appmain.Season'),
        ),
    ]
