# Generated by Django 3.0.1 on 2020-03-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0097_auto_20200312_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_name'], 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
