# Generated by Django 3.0.1 on 2020-03-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0098_auto_20200313_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
    ]
