# Generated by Django 3.0.1 on 2020-03-17 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0100_auto_20200315_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPick2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('pick_score', models.PositiveSmallIntegerField(default=0)),
                ('saved', models.BooleanField(default=False)),
                ('ACONF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ACONF_team', to='appmain.Team')),
                ('ADIV1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ADIV1_team', to='appmain.Team')),
                ('ADIV2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ADIV2_team', to='appmain.Team')),
                ('AWC36', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AWC36_team', to='appmain.Team')),
                ('AWC45', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AWC45_team', to='appmain.Team')),
                ('NCONF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NCONF_team', to='appmain.Team')),
                ('NDIV1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NDIV1_team', to='appmain.Team')),
                ('NDIV2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NDIV2_team', to='appmain.Team')),
                ('NWC36', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NWC36_team', to='appmain.Team')),
                ('NWC45', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NWC45_team', to='appmain.Team')),
                ('SB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SB_team', to='appmain.Team')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pick2_entered', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_pick2_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_post_picks', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.Season')),
            ],
            options={
                'verbose_name': 'post season pick2',
                'verbose_name_plural': 'post season picks2',
                'ordering': ['year', 'user'],
            },
        ),
        migrations.AddIndex(
            model_name='postpick2',
            index=models.Index(fields=['year', 'user'], name='appmain_pos_year_id_6a3052_idx'),
        ),
        migrations.AddConstraint(
            model_name='postpick2',
            constraint=models.UniqueConstraint(fields=('year', 'user'), name='ps_pick_user2'),
        ),
    ]
