# Generated by Django 3.0.1 on 2020-03-17 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0101_auto_20200317_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_type', models.CharField(choices=[('AWC45', 'AFC Wild Card 45'), ('NWC45', 'NFC Wild Card 45'), ('AWC36', 'AFC Wild Card 36'), ('NWC36', 'NFC Wild Card 36'), ('ADIV1', 'AFC Divisional 1'), ('ADIV2', 'AFC Divisional 2'), ('NDIV1', 'NFC Divisional 1'), ('NDIV2', 'NFC Divisional 2'), ('ACONF', 'AFC Conference Champ'), ('NCONF', 'AFC Conference Champ'), ('SB', 'Super Bowl')], default='AWC45', max_length=5)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_game', to='appmain.Game')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.Season')),
            ],
            options={
                'verbose_name': 'post season game',
                'verbose_name_plural': 'post season games',
                'ordering': ['year', 'ps_type'],
            },
        ),
        migrations.AddIndex(
            model_name='postseason',
            index=models.Index(fields=['year', 'ps_type'], name='appmain_pos_year_id_536bbf_idx'),
        ),
        migrations.AddConstraint(
            model_name='postseason',
            constraint=models.UniqueConstraint(fields=('year', 'ps_type'), name='year_type'),
        ),
    ]
