# Generated by Django 3.0.1 on 2020-03-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0102_auto_20200317_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSeason',
        ),
    ]
