# Generated by Django 3.0.1 on 2020-03-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0103_delete_postseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ACONF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ACONF_game', to='appmain.Game')),
                ('ADIV1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ADIV1_game', to='appmain.Game')),
                ('ADIV2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ADIV2_game', to='appmain.Game')),
                ('AWC36', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AWC36_game', to='appmain.Game')),
                ('AWC45', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AWC45_game', to='appmain.Game')),
                ('NCONF', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NCONF_game', to='appmain.Game')),
                ('NDIV1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NDIV1_game', to='appmain.Game')),
                ('NDIV2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NDIV2_game', to='appmain.Game')),
                ('NWC36', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NWC36_game', to='appmain.Game')),
                ('NWC45', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NWC45_game', to='appmain.Game')),
                ('SB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SB_game', to='appmain.Game')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appmain.Season')),
            ],
            options={
                'verbose_name': 'post season game',
                'verbose_name_plural': 'post season games',
                'ordering': ['year'],
            },
        ),
        migrations.AddIndex(
            model_name='postseason',
            index=models.Index(fields=['year'], name='appmain_pos_year_id_a29021_idx'),
        ),
        migrations.AddConstraint(
            model_name='postseason',
            constraint=models.UniqueConstraint(fields=('year',), name='ps_year'),
        ),
    ]
