# Generated by Django 3.0.1 on 2020-03-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0104_auto_20200317_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpick2',
            name='AvtDiv1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AtDiv1_team', to='appmain.Team'),
        ),
        migrations.AddField(
            model_name='postpick2',
            name='AvtDiv2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AtDiv2_team', to='appmain.Team'),
        ),
        migrations.AddField(
            model_name='postpick2',
            name='NvtDiv1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NtDiv1_team', to='appmain.Team'),
        ),
        migrations.AddField(
            model_name='postpick2',
            name='NvtDiv2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NtDiv2_team', to='appmain.Team'),
        ),
    ]
