# Generated by Django 3.0.1 on 2020-03-21 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0105_auto_20200320_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpickgame',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='postpickgame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='postpickgame',
            name='post_pick_head',
        ),
        migrations.RemoveField(
            model_name='postpickgame',
            name='team',
        ),
        migrations.RemoveField(
            model_name='postpickgame',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='PostPick',
        ),
        migrations.DeleteModel(
            name='PostPickGame',
        ),
    ]
