# Generated by Django 3.0.1 on 2020-03-21 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0106_auto_20200320_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostPick2',
            new_name='PostPick',
        ),
        migrations.RemoveIndex(
            model_name='postpick',
            name='appmain_pos_year_id_6a3052_idx',
        ),
        migrations.AddIndex(
            model_name='postpick',
            index=models.Index(fields=['year', 'user'], name='appmain_pos_year_id_b6f97f_idx'),
        ),
    ]
