# Generated by Django 3.0.1 on 2020-03-28 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appmain', '0108_auto_20200325_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField()),
                ('points', models.PositiveSmallIntegerField()),
                ('pick_score', models.PositiveSmallIntegerField(default=0)),
                ('saved', models.BooleanField(default=False)),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_rev_entered', to=settings.AUTH_USER_MODEL)),
                ('koth_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_rev_koth_game', to='appmain.Game')),
                ('koth_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_rev_koth_team', to='appmain.Team')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_rev_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pick_revs', to=settings.AUTH_USER_MODEL)),
                ('wk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pick_rev_wk', to='appmain.Week')),
            ],
            options={
                'verbose_name': 'pick revision',
                'verbose_name_plural': 'pick revisions',
                'ordering': ['user', 'wk'],
            },
        ),
        migrations.AddIndex(
            model_name='pickrevision',
            index=models.Index(fields=['revision', 'user', 'wk'], name='appmain_pic_revisio_2d0954_idx'),
        ),
        migrations.AddConstraint(
            model_name='pickrevision',
            constraint=models.UniqueConstraint(fields=('revision', 'user', 'wk'), name='pickrev_user_wk'),
        ),
    ]
