# Generated by Django 3.0.1 on 2020-03-31 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0111_auto_20200328_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created',
        ),
        migrations.RemoveField(
            model_name='game',
            name='updated',
        ),
    ]
