# Generated by Django 3.0.1 on 2020-04-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0114_auto_20200331_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo_file_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='web_address',
        ),
        migrations.AlterField(
            model_name='team',
            name='city_name',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='conference',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='lose',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='tie',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='win',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='week',
            name='gt',
            field=models.CharField(max_length=4),
        ),
    ]
