# Generated by Django 3.0.1 on 2020-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0115_auto_20200403_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpoint',
            options={'ordering': ['gt'], 'verbose_name': 'post season point', 'verbose_name_plural': 'post season points'},
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('team_abrev',), name='abrev_team'),
        ),
    ]
