# Generated by Django 3.0.1 on 2020-04-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0116_auto_20200404_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_file_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='web_address',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
