# Generated by Django 3.0.1 on 2020-04-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmain', '0117_auto_20200407_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='lose',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tie',
        ),
        migrations.RemoveField(
            model_name='team',
            name='win',
        ),
        migrations.AddField(
            model_name='team',
            name='home_file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='visitor_file_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
